# Generated by Django 2.2.1 on 2019-11-21 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('PE', 'Production Engineer'), ('SE', 'Security Engineer'), ('MG', 'Manager'), ('SA', 'System Administrator')], default='SE', max_length=2)),
                ('score', models.FloatField(default=0.0)),
                ('service', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('PE', 'Production Engineer'), ('SE', 'Security Engineer'), ('MG', 'Manager'), ('SA', 'System Administrator')], default='SE', max_length=2)),
            ],
        ),
    ]
